plugins { id 'com.android.application' }

android {
    namespace 'com.therapyonway.customer'
    compileSdk 35

    defaultConfig {
        applicationId 'com.therapyonway.customer'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.1'
    }
}

// Provider chat release build trigger
